import type { NodeTypeMetadata } from '../types/workflow.js';

export const NODE_TYPES: Record<string, NodeTypeMetadata> = {
  webhook: {
    type: 'webhook',
    category: 'trigger',
    label: 'Webhook',
    description: 'HTTP endpoint trigger',
    color: '#7F77DD',
    icon: 'Zap',
    inputs: 0,
    outputs: 1,
  },
  schedule: {
    type: 'schedule',
    category: 'trigger',
    label: 'Schedule',
    description: 'Cron-based trigger',
    color: '#7F77DD',
    icon: 'Clock',
    inputs: 0,
    outputs: 1,
  },
  manual: {
    type: 'manual',
    category: 'trigger',
    label: 'Manual Trigger',
    description: 'Manual execution trigger',
    color: '#7F77DD',
    icon: 'Play',
    inputs: 0,
    outputs: 1,
  },
  'code-js': {
    type: 'code-js',
    category: 'logic',
    label: 'Code (JavaScript)',
    description: 'Execute JavaScript in sandbox',
    color: '#1D9E75',
    icon: 'Code',
    inputs: 1,
    outputs: 1,
  },
  'code-python': {
    type: 'code-python',
    category: 'logic',
    label: 'Code (Python)',
    description: 'Execute Python script',
    color: '#1D9E75',
    icon: 'Code',
    inputs: 1,
    outputs: 1,
  },
  if: {
    type: 'if',
    category: 'logic',
    label: 'IF',
    description: 'Boolean condition branching',
    color: '#BA7517',
    icon: 'GitBranch',
    inputs: 1,
    outputs: 2,
  },
  switch: {
    type: 'switch',
    category: 'logic',
    label: 'Switch',
    description: 'Multi-branch routing',
    color: '#BA7517',
    icon: 'GitBranch',
    inputs: 1,
    outputs: 4,
  },
  merge: {
    type: 'merge',
    category: 'logic',
    label: 'Merge',
    description: 'Combine data from multiple paths',
    color: '#BA7517',
    icon: 'GitMerge',
    inputs: 2,
    outputs: 1,
  },
  loop: {
    type: 'loop',
    category: 'logic',
    label: 'Loop',
    description: 'Iterate over items',
    color: '#BA7517',
    icon: 'Repeat',
    inputs: 1,
    outputs: 1,
  },
  set: {
    type: 'set',
    category: 'logic',
    label: 'Set',
    description: 'Set/transform data fields',
    color: '#1D9E75',
    icon: 'PenLine',
    inputs: 1,
    outputs: 1,
  },
  'http-request': {
    type: 'http-request',
    category: 'integration',
    label: 'HTTP Request',
    description: 'Make HTTP requests',
    color: '#D85A30',
    icon: 'Globe',
    inputs: 1,
    outputs: 1,
  },
  'ai-agent': {
    type: 'ai-agent',
    category: 'integration',
    label: 'AI Agent',
    description: 'LLM with tool calling',
    color: '#D4537E',
    icon: 'Bot',
    inputs: 1,
    outputs: 1,
  },
  'respond-webhook': {
    type: 'respond-webhook',
    category: 'output',
    label: 'Respond Webhook',
    description: 'Return HTTP response to caller',
    color: '#888780',
    icon: 'Send',
    inputs: 1,
    outputs: 0,
  },
};

export const NODE_CATEGORIES = {
  trigger: { label: 'Triggers', color: '#7F77DD' },
  logic: { label: 'Logic', color: '#1D9E75' },
  integration: { label: 'Integration', color: '#D85A30' },
  output: { label: 'Output', color: '#888780' },
} as const;
