import type { Workflow } from '@flowaibuilder/shared';
import { topoSort } from '../topo.js';

function pyRepr(value: unknown, indentLevel = 0): string {
  const pad = '    '.repeat(indentLevel);
  const padInner = '    '.repeat(indentLevel + 1);
  if (value === null || value === undefined) return 'None';
  if (typeof value === 'boolean') return value ? 'True' : 'False';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'None';
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map((v) => `${padInner}${pyRepr(v, indentLevel + 1)}`);
    return `[\n${items.join(',\n')}\n${pad}]`;
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return '{}';
    const items = entries.map(
      ([k, v]) => `${padInner}${JSON.stringify(k)}: ${pyRepr(v, indentLevel + 1)}`,
    );
    return `{\n${items.join(',\n')}\n${pad}}`;
  }
  return 'None';
}

export function compilePython(workflow: Workflow): string {
  const { nodes: ordered, hasCycle } = topoSort(workflow.nodes, workflow.connections);

  const header: string[] = [];
  if (hasCycle) header.push('# cycle detected — falling back to insertion order');
  header.push('# Generated by flowAIbuilder export — DO NOT EDIT');
  header.push('from flowaibuilder import define_workflow, node, connection  # notional SDK');
  header.push('');

  const nodeLiterals = ordered.map((n) =>
    pyRepr(
      {
        id: n.id,
        type: n.type,
        name: n.name,
        position: n.position,
        data: { config: n.data?.config ?? {} },
      },
      2,
    ),
  );

  const connLiterals = workflow.connections.map((c) => {
    const literal: Record<string, unknown> = {
      id: c.id,
      sourceNodeId: c.sourceNodeId,
      targetNodeId: c.targetNodeId,
    };
    if (c.sourceHandle) literal.sourceHandle = c.sourceHandle;
    if (c.targetHandle) literal.targetHandle = c.targetHandle;
    return pyRepr(literal, 2);
  });

  const body =
    `workflow = define_workflow(\n` +
    `    id=${JSON.stringify(workflow.id)},\n` +
    `    name=${JSON.stringify(workflow.name)},\n` +
    `    description=${JSON.stringify(workflow.description ?? '')},\n` +
    `    nodes=[\n${nodeLiterals.map((l) => '        ' + l).join(',\n')}\n    ],\n` +
    `    connections=[\n${connLiterals.map((l) => '        ' + l).join(',\n')}\n    ],\n` +
    `)\n`;

  return header.join('\n') + '\n' + body;
}
