import type { Workflow } from '@flowaibuilder/shared';
import { topoSort } from '../topo.js';

function unquoteKeys(jsonText: string): string {
  return jsonText.replace(/^(\s*)"([a-zA-Z_$][a-zA-Z0-9_$]*)":/gm, '$1$2:');
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((l) => (l.length ? pad + l : l))
    .join('\n');
}

export function compileTypeScript(workflow: Workflow): string {
  const { nodes: ordered, hasCycle } = topoSort(workflow.nodes, workflow.connections);

  const header: string[] = [];
  if (hasCycle) header.push('// cycle detected — falling back to insertion order');
  header.push('// Generated by flowAIbuilder export — DO NOT EDIT');
  header.push("// Notional SDK — Story 4.1 generates the shape, runtime SDK is future work.");
  header.push("import { defineWorkflow, node, connection } from '@flowaibuilder/sdk';");
  header.push('');

  const nodeLiterals = ordered.map((n) => {
    const literal = {
      id: n.id,
      type: n.type,
      name: n.name,
      position: n.position,
      data: { config: n.data?.config ?? {} },
    };
    return indent(unquoteKeys(JSON.stringify(literal, null, 2)), 4);
  });

  const connLiterals = workflow.connections.map((c) => {
    const literal: Record<string, unknown> = {
      id: c.id,
      sourceNodeId: c.sourceNodeId,
      targetNodeId: c.targetNodeId,
    };
    if (c.sourceHandle) literal.sourceHandle = c.sourceHandle;
    if (c.targetHandle) literal.targetHandle = c.targetHandle;
    return indent(unquoteKeys(JSON.stringify(literal, null, 2)), 4);
  });

  const body =
    `export const workflow = defineWorkflow({\n` +
    `  id: ${JSON.stringify(workflow.id)},\n` +
    `  name: ${JSON.stringify(workflow.name)},\n` +
    `  description: ${JSON.stringify(workflow.description ?? '')},\n` +
    `  nodes: [\n${nodeLiterals.join(',\n')}\n  ],\n` +
    `  connections: [\n${connLiterals.join(',\n')}\n  ],\n` +
    `});\n`;

  return header.join('\n') + '\n' + body;
}
